---
- hosts: localhost
  connection: local
  vars_files:
    - vars/generic.yml

  tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - 'vars/{{ vault_global_generated_for_ansible_file_prefix }}06_fileshare.yml'
    ignore_errors: true

  - name: output dir
    file:
      path: '../output'
      state: directory

  - name: Generate docs
    template:
      src: 'templates/doc.infra.md'
      dest: '../output/README.md'

  - name: Generate Url Shortcut
    template:
      src: 'templates/windows_url_shortcut.url.j2'
      dest: '../output/guac.{{ public_hosting_domain }}.url'
    loop:
      - { url: 'https://guac.{{ public_hosting_domain }}'}

  - name: rdp dir
    file:
      path: '../output/rdp'
      state: directory

  - name: Generate rdp files
    include_tasks: tasks/linux_rdp_file.yml
    vars:
      # rdp_file_username: '{{ vault_global_admin_user }}@{{ dns_domain_name }}'
      rdp_file_full_address: '{{ item }}.{{ dns_domain_name }}'
      rdp_file_gatewayhostname: 'rdg.{{ public_hosting_domain }}'
      rdp_file_dest: '../output/rdp/{{ item }}.rdp'
    loop: '{{ groups["windows"] }}'

  - name: Generate rdp files
    include_tasks: tasks/linux_rdp_file.yml
    vars:
      # rdp_file_username: '{{ vault_global_admin_user }}@{{ dns_domain_name }}'
      rdp_file_full_address: '{{ item }}.{{ dns_domain_name }}'
      rdp_file_gatewayhostname: 'rdg.{{ public_hosting_domain }}'
      rdp_file_dest: '../output/rdp/{{ item }}-lbc.rdp'
      rdp_file_load_balance_info: 'tsv://MS Terminal Services Plugin.1.{{ rds_session_collection_name }}'
      rdp_file_alternate_full_address: '{{ item }}.{{ dns_domain_name }}'
      rdp_file_workspace_id: '{{ item }}.{{ dns_domain_name }}'
    loop: '{{ groups["windows_rdcb"] }}'
    when: '"windows_rdcb" in groups'
