---
- hosts: linux-guacamole
  become: true
  vars_files:
    - vars/generic.yml

  roles:
    - { role: ansible-role-docker }

  tasks:
    - name: generic-dh - Install docker python sdk
      pip:
        name: docker
